Ictshop/Controllers/DanhmucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ictshop.Models;

namespace Ictshop.Controllers
{
    public class DanhmucController : Controller
    {
        Qlbanhang db = new Qlbanhang();
        // GET: Danhmuc
        public ActionResult DanhmucPartial()
        {
            var danhmuc = db.Hangsanxuats.ToList();
            return PartialView(danhmuc);
        }
        public ActionResult Manufacturer(int mahangsx) {
            var hangsx = db.Hangsanxuats.SingleOrDefault(n => n.Mahang == mahangsx);
            return PartialView(hangsx);
        }
        public ActionResult ListManufacturers(int mahangsx, string tenhangsx)
        {
            var sanpham = db.Sanphams.Where(n=> n.Mahang == mahangsx).ToList();
            return View(sanpham);
        }
    }
}

Ictshop/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ictshop.Models;

namespace Ictshop.Controllers
{
    public class SanphamController : Controller
    {
        Qlbanhang db = new Qlbanhang();

        // GET: Sanpham
        public ActionResult hangsx()
        {
            var Hangsx = db.Hangsanxuats.ToList();
            return PartialView(Hangsx);
        }
        public ActionResult sanpham(int Mahang)
        {
            var ss = db.Sanphams.Where(n => n.Mahang == Mahang).Take(4).ToList();
            return PartialView(ss);
        }
        public ActionResult timkiem(string name)
        {
            var sanpham = db.Sanphams.ToList();

            if (!string.IsNullOrWhiteSpace(name))
            {
                sanpham = sanpham.Where(n => n.Tensp.ToLower().Contains(name.ToLower())).ToList();
            }

            return View(sanpham);

        }
        public ActionResult xemchitiet(int Masp)
        {
            var chitiet = db.Sanphams.Include("Hedieuhanh").Include("Hangsanxuat").SingleOrDefault(n=>n.Masp== Masp);
            if (chitiet == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(chitiet);
        }

    }

}

Ictshop/Views/Danhmuc/DanhmucPartial.cshtml
@using Ictshop.Models;
@model List<Hangsanxuat>

<style>
    .index{
        font-size:16px;
        padding:5px;
        border:1px dashed black;
        & li{
              list-style-type:none;
              width:auto;
              text-align:center;
              & a{
                    text-decoration: none

                 }
            }
    }
</style>

<br />

<div class="bg-success" style="padding:10px 5px">

    <h3> DANH MỤC  </h3>

    <div  style="display:flex; gap:10px;width:100%; padding: 0 10px">

        @foreach (var item in Model)
        {
            <div class="col-lg-1 index">
                <li class="success">@Html.ActionLink(item.Tenhang, "Manufacturer", "DanhMuc", new { mahangsx = item.Mahang, tenhangsx = item.Tenhang }, null)</li>
            </div>
        }
    </div>
</div>

Ictshop/Views/Danhmuc/ListManufacturers.cshtml
<style>
    .btn-add-to-cart {
        padding: 7px 15px;
        border-radius: 5px;
        border-width: 1px;
        border-color: dodgerblue;
        color: dodgerblue;
        font-weight: 600;
        background: white;
    }

    .product {
        display: grid;
        grid-template-columns: repeat(4, 1fr);
        gap: 40px 10px;
        & > div

    {
        width: 100%;
    }
    }
</style>

@if (Model != null && Model.Count > 0)
{
    <div class="product">
        @foreach (var item in Model)
        {
            <div class="col-md-3 col-sm-6">
                <a href="@Url.Action("xemchitiet","Sanpham", new {@Masp=item.Masp })">
                    <img src=@Url.Content("~" +item.Anhbia.ToString()) class="img-responsive" alt="" width="400" height="400" />
                </a>
                <center>
                    <h3>@item.Tensp</h3>
                    <h3 style="color:red">Giá: @String.Format("{0:0,0}", @item.Giatien) VND</h3>
                    <br />
                    @using (Html.BeginForm("ThemGioHang", "GioHang", new { @iMasp = item.Masp, @strURL = Request.Url.ToString() }))
                    {
                        <input type="submit" value="Thêm vào giỏ hàng" id="bgnGioHang" class="btn-add-to-cart" />
                    }
                    @*<a href="@Url.Action("xemchitiet", new {@Masp=item.Masp })">Xem chi tiết</a>*@
                </center>

            </div>
        }
    </div>

}
else
{
    <center style="padding:75px 40px">
        <div><h3>Không có sản phẩm nào!</h3></div>
    </center>
}

Ictshop/Views/Danhmuc/Manufacturer.cshtml
<div style="margin-top:70px">
    <div style="background: #c5c5c585; padding: 8px 10px; border-radius: 7px; max-width: 1200px; margin: 0 auto;">
        <h2>Hãng sản xuất: @Model.Tenhang</h2>
    </div>
    @Html.Action("ListManufacturers", "Danhmuc")
</div>